source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "webrick", "~> 1.8"

# Ruby stdlib gems that stopped auto-loading in Ruby 3.4+
gem "csv"
gem "bigdecimal"

# Jekyll plugins used in _config.yml
gem "jekyll-feed", "~> 0.17"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-include-cache", "~> 0.2", group: :jekyll_plugins
gem "jekyll-remote-theme", "~> 0.4.3", group: :jekyll_plugins
gem "jekyll-paginate", "~> 1.1"
